rating_aggregator/main/routes.py
import flask
from flask import render_template, url_for, flash, request, redirect, abort, Blueprint, current_app
from rating_aggregator import db, bcrypt, mail
from rating_aggregator.models import User, Movie, WatchlistMovies
from rating_aggregator.get_ratings import get_all_ratings
from sqlalchemy import desc, asc, func
from rating_aggregator.users.forms import registrationForm, loginForm, UpdateDetailsForm, RequestResetForm, ResetPasswordForm
from rating_aggregator.movies.forms import TitleSearchForm, ResultsSearchForm, YearSearchForm
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message

main = Blueprint('main', __name__)

# Route for help page
@main.route('/help', methods=['GET', 'POST'])
def help():
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('movies.title_results', name=search_form.movie_title.data.lower().strip()))
    return render_template('help.html', title='Help', search_form=search_form)

#<--------------------Error Handling------------------->

"""
# Route for 403 custom error page
@main.errorhandler(403)
def forbidden_page(e):
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('title_results', name=search_form.movie_title.data.lower()))

    return render_template('403.html', title='403', search_form=search_form), 403

# Route for 404 custom error page
@main.errorhandler(404)
def not_found_page(e):
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('title_results', name=search_form.movie_title.data.lower()))

    return render_template('404.html', title='404', search_form=search_form), 404
"""

rating_aggregator/users/routes.py
import flask
from flask import render_template, url_for, flash, request, redirect, abort, Blueprint, current_app
from rating_aggregator import db, bcrypt, mail
from rating_aggregator.models import User, Movie, WatchlistMovies
from rating_aggregator.get_ratings import get_all_ratings
from sqlalchemy import desc, asc, func
from rating_aggregator.users.forms import registrationForm, loginForm, UpdateDetailsForm, RequestResetForm, ResetPasswordForm
from rating_aggregator.movies.forms import TitleSearchForm, ResultsSearchForm, YearSearchForm
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message
from rating_aggregator.users.utils import send_reset_email

users = Blueprint('users', __name__)

#<--------------------User Endpoints------------------->

# Route to register a new user
@users.route('/register', methods=['GET', 'POST'])
def register():
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('movies.title_results', name=search_form.movie_title.data.lower().strip()))

    if current_user.is_authenticated:
        flash('You are already logged in with a registered account!', 'danger')
        return redirect(url_for('movies.get_all_movies'))

    register_form = registrationForm()
    if register_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(register_form.password.data).decode('utf-8')
        user = User(forename=register_form.forename.data, surname=register_form.surname.data.strip(), email=register_form.email.data.strip(), password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account successfully created. You can now log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register an account', register_form=register_form, search_form=search_form)

# Route to login a registered user
@users.route('/login', methods=['GET', 'POST'])
def login():
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('movies.title_results', name=search_form.movie_title.data.lower().strip()))

    if current_user.is_authenticated:
        flash('You are already logged in with a registered account!', 'danger')
        return redirect(url_for('movies.get_all_movies'))
    else:
        login_form = loginForm()
        if login_form.validate_on_submit():
            user = User.query.filter_by(email=login_form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, login_form.password.data): # check if both hashed passwords are equal
                login_user(user)
                # access page user was trying to access before login
                next_page = request.args.get('next')
                flash('Login successful!', 'success')
                return redirect(next_page) if next_page else redirect(url_for('movies.get_all_movies'))
            else:
                flash('Login unsuccessful, please check you have input the correct email and password!', 'danger')
    return render_template('login.html', title='Log in to your account', login_form=login_form, search_form=search_form)

# Route to log user out
@users.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash('User successfully logged out', 'success')
    return redirect(url_for('movies.get_all_movies'))

# Route to view user's profile
@users.route('/users/<user_id>', methods=['GET', 'POST'])
@login_required
def profile(user_id):
    update_form = UpdateDetailsForm()
    if current_user.is_authenticated:
        if current_user.admin:
            user = User.query.filter_by(id=user_id).first()
            if update_form.validate_on_submit():
                user.forename = update_form.forename.data.strip()
                user.surname = update_form.surname.data.strip()
                if update_form.email.data.strip() != user.email:
                    other_user = User.query.filter_by(email=update_form.email.data).first()
                    if other_user:
                        flash('This email is in use, please use a different one!', 'danger')
                    else:
                        user.email = update_form.email.data.strip()
                        db.session.commit()
                        flash('Account details successfully updated!', 'success')
                else:
                    db.session.commit()
                    flash('Account details successfully updated!', 'success')
                return redirect(url_for('users.profile', user_id=user.id))
            elif request.method == 'GET':
                # Populate form with users current details
                update_form.forename.data = user.forename
                update_form.surname.data = user.surname
                update_form.email.data = user.email
        elif not current_user.admin:
            if update_form.validate_on_submit():
                current_user.forename = update_form.forename.data
                current_user.surname = update_form.surname.data
                current_user.email = update_form.email.data
                db.session.commit()
                flash('Account details successfully updated!', 'success')
                return redirect(url_for('users.profile', user_id=current_user.id))
            elif request.method == 'GET':
                # Populate form with users current details
                update_form.forename.data = current_user.forename
                update_form.surname.data = current_user.surname
                update_form.email.data = current_user.email
    else:
        abort(403)

    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('movies.title_results', name=search_form.movie_title.data.lower().strip()))

    return render_template('profile.html', title='Profile', search_form=search_form, update_form=update_form)

# Route to request password reset
@users.route('/reset_password', methods=['GET', 'POST'])
def request_reset():
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('movies.title_results', name=search_form.movie_title.data.lower().strip()))

    if current_user.is_authenticated:
        flash('You are already logged in with a registered account!', 'danger')
        return redirect(url_for('movies.get_all_movies'))
    reset_form = RequestResetForm()
    if reset_form.validate_on_submit():
        user = User.query.filter_by(email=reset_form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'success')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title='Reset Password', search_form=search_form, reset_form=reset_form)

# Route to reset password with acquired token
@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('movies.title_results', name=search_form.movie_title.data.lower().strip()))

    if current_user.is_authenticated:
        flash('You are already logged in with a registered account!', 'danger')
        return redirect(url_for('movies.get_all_movies'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is an invalid or expired token', 'danger')
        return redirect(url_for('users.request_reset'))
    password_reset_form = ResetPasswordForm()
    if password_reset_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(password_reset_form.password.data).decode('utf-8')
        user.password =  hashed_password
        db.session.commit()
        flash('Your password has been successfully updated. You can now log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', search_form=search_form, password_reset_form=password_reset_form)

#<--------------------User Watchlist------------------->

# Route to view user's watchlist
@users.route('/users/<user_id>/watchlist', methods=['GET', 'POST'])
@login_required
def get_watchlist(user_id):
    search_form = TitleSearchForm()
    if flask.request.method == 'POST' and search_form.validate_on_submit():
        return redirect(url_for('movies.title_results', name=search_form.movie_title.data.lower().strip()))

    movies = []

    watchlist = WatchlistMovies.query.filter_by(userId=current_user.id).all()
    for entry in watchlist:
        movie = Movie.query.filter_by(movieId=entry.movieId).first()
        movies.append(movie)
    return render_template('watchlist.html', title='Watchlist', search_form=search_form, movies=movies)

# Route to add a movie to watchlist
@users.route('/users/<user_id>/watchlist/add/movies/<movie_id>/<name>_<year>', methods=['POST'])
@login_required
def add_to_watchlist(user_id, movie_id, name, year):
    movie = WatchlistMovies.query.filter_by(userId=user_id, movieId=movie_id).first()
    if movie:
        flash('Movie already exists in watchlist!', 'danger')
        return redirect(request.referrer)
    else:
        movie = WatchlistMovies(userId=user_id, movieId=movie_id)
        db.session.add(movie)
        db.session.commit()
        flash('Movie added to watchlist!', 'success')
        return redirect(request.referrer)

# Route to delete a movie from watchlist
@users.route('/users/<user_id>/watchlist/delete/movies/<movie_id>/<name>_<year>', methods=['POST'])
@login_required
def delete_from_watchlist(user_id, movie_id, name, year):

rating_aggregator/templates/all_movies.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="page_tites">All Movies</h1>
    <div class="movie-page-grid">
        {% for movie in movies %}
            <div class="image-container" style="margin-right: 1rem;">
                <span title="View Movie Details">
                    <a href="{{ url_for('movies.search_for_movie', name=movie.title, year=movie.year) }}" style="display: inline-block;">
                        <img style="width: auto; height: auto; margin: auto; max-width:450px; max-height:450px; display: block; border: 2px solid black;" src="{{ movie.movie_image }}">
                        <div class="overlay">
                            {% if current_user.is_authenticated %}
                                {% if movie in watchlist_entries %}
                                    <form action='{{ url_for("users.delete_from_watchlist", user_id=current_user.id, movie_id=movie.movieId, name=movie.title, year=movie.year) }}' method=post style="float: right;">
                                        <button type="submit" name="remove_movie" style="border: none; background: none;">
                                            <span title="Remove from watchlist"><i class="fa fa-trash trash-button" style="font-size: 1.5rem;"></i></span>
                                        </button>
                                    </form>
                                {% else %}
                                    <form action='{{ url_for("users.add_to_watchlist", user_id=current_user.id, movie_id=movie.movieId, name=movie.title, year=movie.year) }}' method=post style="float: right;">
                                        <button type="submit" name="add_movie" style="border: none; background: none;">
                                            <span title="Add to watchlist"><i class="fa fa-plus-square trash-button" style="font-size: 1.5rem;"></i></span>
                                        </button>
                                    </form>
                                {% endif %}
                            {% endif %}
                            <div class="movie-grid-titles">
                                <div style=" font-size: 1.1rem; float: left;">{{ movie["title"] }} ({{ movie["year"] }})</br></div>
                            </div>
                            <span title="Overall Weighted Rating">
                                {% if movie.average_rating >= 60 %}
                                    <div class="rating-circle" style="width: 140px; height: 140px; line-height: 140px; font-size: 40px; border: 2px solid black; margin-top: 2rem;">{{ (movie["average_rating"]|string).rstrip('0').rstrip('.') }}</div>
                                {% else %}
                                    <div class="rating-circle" style="width: 140px; height: 140px; line-height: 140px; font-size: 40px; border: 2px solid black; margin-top: 2rem; background-color: red;">{{ (movie["average_rating"]|string).rstrip('0').rstrip('.') }}</div>
                                {% endif %}
                            </span>
                        </div>
                    </a>
                </span>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

rating_aggregator/templates/get_favourable_movies.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="page_tites">Favourable Ratings</h1>
    <div class="movie-page-grid">
        {% for movie in movies %}
            <div class="image-container" style="margin-right: 1rem;">
                <span title="View Movie Details">
                    <a href="{{ url_for('movies.search_for_movie', name=movie.title, year=movie.year) }}" style="display: inline-block;">
                        <img style="width: auto; height: auto; margin: auto; max-width:450px; max-height:450px; display: block; border: 2px solid black;" src="{{ movie.movie_image }}">
                        <div class="overlay">
                            {% if current_user.is_authenticated %}
                                {% if movie in watchlist_entries %}
                                    <form action='{{ url_for("users.delete_from_watchlist", user_id=current_user.id, movie_id=movie.movieId, name=movie.title, year=movie.year) }}' method=post style="float: right;">
                                        <button type="submit" name="remove_movie" style="border: none; background: none;">
                                            <span title="Remove from watchlist"><i class="fa fa-trash trash-button" style="font-size: 1.5rem;"></i></span>
                                        </button>
                                    </form>
                                {% else %}
                                    <form action='{{ url_for("users.add_to_watchlist", user_id=current_user.id, movie_id=movie.movieId, name=movie.title, year=movie.year) }}' method=post style="float: right;">
                                        <button type="submit" name="add_movie" style="border: none; background: none;">
                                            <span title="Add to watchlist"><i class="fa fa-plus-square trash-button" style="font-size: 1.5rem;"></i></span>
                                        </button>
                                    </form>
                                {% endif %}
                            {% endif %}
                            <div class="movie-grid-titles">
                                <div style=" font-size: 1.1rem; float: left;">{{ movie["title"] }} ({{ movie["year"] }})</br></div>
                            </div>
                            <span title="Overall Weighted Rating">
                                {% if movie.average_rating >= 60 %}
                                    <div class="rating-circle" style="width: 140px; height: 140px; line-height: 140px; font-size: 40px; border: 2px solid black; margin-top: 2rem;">{{ (movie["average_rating"]|string).rstrip('0').rstrip('.') }}</div>
                                {% else %}
                                    <div class="rating-circle" style="width: 140px; height: 140px; line-height: 140px; font-size: 40px; border: 2px solid black; margin-top: 2rem; background-color: red;">{{ (movie["average_rating"]|string).rstrip('0').rstrip('.') }}</div>
                                {% endif %}
                            </span>
                        </div>
                    </a>
                </span>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

rating_aggregator/templates/get_hightolow_ratings.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="page_tites">High to Low Ratings</h1>
    <div class="movie-page-grid">
        {% for movie in movies %}
            <div class="image-container" style="margin-right: 1rem;">
                <span title="View Movie Details">
                    <a href="{{ url_for('movies.search_for_movie', name=movie.title, year=movie.year) }}" style="display: inline-block;">
                        <img style="width: auto; height: auto; margin: auto; max-width:450px; max-height:450px; display: block; border: 2px solid black;" src="{{ movie.movie_image }}">
                        <div class="overlay">
                            {% if current_user.is_authenticated %}
                                {% if movie in watchlist_entries %}
                                    <form action='{{ url_for("users.delete_from_watchlist", user_id=current_user.id, movie_id=movie.movieId, name=movie.title, year=movie.year) }}' method=post style="float: right;">
                                        <button type="submit" name="remove_movie" style="border: none; background: none;">
                                            <span title="Remove from watchlist"><i class="fa fa-trash trash-button" style="font-size: 1.5rem;"></i></span>
                                        </button>
                                    </form>
                                {% else %}
                                    <form action='{{ url_for("users.add_to_watchlist", user_id=current_user.id, movie_id=movie.movieId, name=movie.title, year=movie.year) }}' method=post style="float: right;">
                                        <button type="submit" name="add_movie" style="border: none; background: none;">
                                            <span title="Add to watchlist"><i class="fa fa-plus-square trash-button" style="font-size: 1.5rem;"></i></span>
                                        </button>
                                    </form>
                                {% endif %}
                            {% endif %}
                            <div class="movie-grid-titles">
                                <div style=" font-size: 1.1rem; float: left;">{{ movie["title"] }} ({{ movie["year"] }})</br></div>
                            </div>
                            <span title="Overall Weighted Rating">
                                {% if movie.average_rating >= 60 %}
                                    <div class="rating-circle" style="width: 140px; height: 140px; line-height: 140px; font-size: 40px; border: 2px solid black; margin-top: 2rem;">{{ (movie["average_rating"]|string).rstrip('0').rstrip('.') }}</div>
                                {% else %}
                                    <div class="rating-circle" style="width: 140px; height: 140px; line-height: 140px; font-size: 40px; border: 2px solid black; margin-top: 2rem; background-color: red;">{{ (movie["average_rating"]|string).rstrip('0').rstrip('.') }}</div>
                                {% endif %}
                            </span>
                        </div>
                    </a>
                </span>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

rating_aggregator/templates/layout.html
<!doctype html>
<html>
    <head>
        <link rel='stylesheet' href="{{ url_for('static', filename='font-awesome-4.7.0/css/font-awesome.min.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        {% if title %}
            <title>{{ title }} - Movie Rating Aggregator</title>
        {% else %}
            <title>Movie Rating Aggregator</title>
        {% endif %}
    </head>
    <body class="container">
        <div class="content">
            <header class="header">
                <h1><a href="{{ url_for('movies.get_all_movies') }}"><i class="fa fa-film header-logo"></i>Movie Rating Aggregator</a></h1>
                <form method="POST" action="" class="form-control">
                    {{ search_form.hidden_tag() }}
                    <div style="padding-right: 2rem;">
                        {% if search_form.movie_title.errors %}
                            {{ search_form.movie_title(class_="title-search-control") }}
                        {% else %}
                            {{ search_form.movie_title(class_="title-search-control") }}
                        {% endif %}
                    </div>
                    <div>
                        <button type="submit" class="title-search-button"><i class="fa fa-search" style="text-align: center;"></i></button>
                    </div>
                </form>
            </header>
            <div class="sidebar-container">
                <div class="sidebar">
                    <h1><i class="fa fa-bars"></i> Menu</h1>
                    <ul>
                        <button class="dropdown-btn">Movies 
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <li><a href="{{ url_for('movies.get_all_movies') }}">All Movies</a></li>
                            <li><a href="{{ url_for('movies.get_high_to_low_ratings') }}">High-to-Low</a></li>
                            <li><a href="{{ url_for('movies.get_low_to_high_ratings') }}">Low-to-High</a></li>
                            <li><a href="{{ url_for('movies.get_favourable_reviews') }}">Favourable</a></li>
                            <li><a href="{{ url_for('movies.get_nonfavourable_reviews') }}">Non-Favourable</a></li>
                            <li><a href="{{ url_for('movies.get_top10_movies') }}">Top 10</a></li>
                            <li><a href="{{ url_for('movies.search_movies_by_year') }}">Search By Year</a></li>
                        </div>
                        {% if current_user.is_authenticated %}
                            {% if current_user.admin %}
                                <button class="dropdown-btn">Admin 
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="dropdown-container">
                                    <li><a href="{{ url_for('users.get_all_users') }}", style="padding-left: 0.5rem;">All Users
                                        <i class="fa fa-user" style="float: left;"></i>
                                    </a></li>
                                </div>
                            {% endif %}
                            <button class="dropdown-btn">User 
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="dropdown-container">
                                <li><a href="{{ url_for('users.profile', user_id=current_user.id) }}", style="padding-left: 0.5rem;">Profile
                                    <i class="fa fa-user" style="float: left;"></i>
                                </a></li>
                                <li><a href="{{ url_for('users.get_watchlist', user_id=current_user.id) }}", style="padding-left: 0.5rem;">Watchlist
                                    <i class="fa fa-eye", style="float: left;"></i>
                                </a></li>
                            </div>
                            <li>
                                <button class="logout-button" onclick="document.getElementById('logout-modal').style.display='block'">Logout <i class="fa fa-sign-out" style="float: left; padding-right: 0.5rem;"></i></button>
                            </a></li>
                        {% else %}
                            <li><a href="{{ url_for('users.login') }}" style="padding-left: 0.5rem;">Login <i class="fa fa-sign-out" style="float: left; padding-left: 0.5rem;"></i></a></li>
                            <li><a href="{{ url_for('users.register') }}" style="padding-left: 0.5rem;">Register <i class="fa fa-user-plus" style="float: left; padding-left: 0.5rem;"></i></a></li>
                        {% endif %}
                        <li><a href="{{ url_for('main.help') }}" style="padding-left: 0.5rem;">Help <i class="fa fa-question-circle" style="float: left; padding-left: 0.5rem;"></i></a></li>
                    </ul>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div id="flash-messages" class="flash-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="body">
                <div>
                    <div id="logout-modal" class="modal">
                        <form class="modal-content" action='{{ url_for("users.logout") }}' method=get>
                        <div class="modal-container" style="font-family: sans-serif;">
                            <span onclick="document.getElementById('logout-modal').style.display='none'" class="close" title="Close">&times;</span>
                            <h1 style="color: black;">Logout</h1>
                            <p>Are you sure you want to log out of your account?</p>
                    
                            <div class="clearfix">
                                <button type="button" class="cancelbtn" onclick="document.getElementById('logout-modal').style.display='none'" class="close" title="Cancel">Cancel</button>
                                <input type=submit class="deletebtn" value="Logout">
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

<script>
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;

    for (i = 0; i < dropdown.length; i++) {
        dropdown[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
        });
    }
</script>

<script type="text/javascript">window.setTimeout("document.getElementById('flash-messages').style.display='none';", 3000); </script>

rating_aggregator/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="page_tites" style="padding-bottom: 2rem;">User Login</h1>
    <div style="text-align: center;">
        <div style="float: left; position: relative; left: 50%;">
            <div style="float: left; position: relative; left: -50%;">
                <form method="POST" action="">
                    {{ login_form.hidden_tag() }}
                    <div style="color: whitesmoke; font-family: sans-serif; font-weight: bold;">
                        {% if login_form.email.errors %}
                            {{ login_form.email(class_="login-form-control") }}
                            <div class="form-errors">
                                {% for error in login_form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ login_form.email(class_="login-form-control") }}
                        {% endif %}
                    </div>
                    <div style="color: whitesmoke; font-family: sans-serif; font-weight: bold;">
                        {% if login_form.password.errors %}
                            {{ login_form.password(class_="login-form-control") }}
                            <div class="form-errors">
                                {% for error in login_form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ login_form.password(class_="login-form-control") }}
                        {% endif %}
                    </div>
                    <div>
                        {{ login_form.login_button(class_="login-form-button") }}
                    </div>
                </form>
                <div class="register_small_text">
                    <small>
                        <a href="{{ url_for('users.register')  }}" class="all-small">Don't have an account?</a>
                    </small></br>
                    <small>
                        <a href="{{ url_for('users.request_reset')  }}" class="all-small">Forgot your password?</a>
                    </small>
                </div>
            </div>
    </div>
{% endblock content %}